version: '3.8'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=micronaut_demo
      - POSTGRES_USER=micronaut
      - POSTGRES_PASSWORD=demo
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
