micronaut:
  application:
    name: micronautDemo
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/micronaut_demo
    username: micronaut
    password: 'demo'
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
flyway:
  datasources:
    default:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3
